// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWuettsoc4gKsqzlmwCdMANePHKcLwYZc',
    appId: '1:198283824428:web:3158f5e08a029239bd7089',
    messagingSenderId: '198283824428',
    projectId: 'fashion-store-d2417',
    authDomain: 'fashion-store-d2417.firebaseapp.com',
    storageBucket: 'fashion-store-d2417.firebasestorage.app',
    measurementId: 'G-9P0HM5QK4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2d5ofHN4h4mxdKWAO7Hrt_wCBRz6fAgk',
    appId: '1:198283824428:android:d5dc61531a8852c7bd7089',
    messagingSenderId: '198283824428',
    projectId: 'fashion-store-d2417',
    storageBucket: 'fashion-store-d2417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIuPM0IZI2ixryzfnXw7Jc_hmUbH8cjPk',
    appId: '1:198283824428:ios:695051acf961a1e9bd7089',
    messagingSenderId: '198283824428',
    projectId: 'fashion-store-d2417',
    storageBucket: 'fashion-store-d2417.firebasestorage.app',
    iosClientId: '198283824428-sbansc4mk6gop1o7qap98a57m2s6ca88.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIuPM0IZI2ixryzfnXw7Jc_hmUbH8cjPk',
    appId: '1:198283824428:ios:695051acf961a1e9bd7089',
    messagingSenderId: '198283824428',
    projectId: 'fashion-store-d2417',
    storageBucket: 'fashion-store-d2417.firebasestorage.app',
    iosClientId: '198283824428-sbansc4mk6gop1o7qap98a57m2s6ca88.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWuettsoc4gKsqzlmwCdMANePHKcLwYZc',
    appId: '1:198283824428:web:b80e6ebbbae76b65bd7089',
    messagingSenderId: '198283824428',
    projectId: 'fashion-store-d2417',
    authDomain: 'fashion-store-d2417.firebaseapp.com',
    storageBucket: 'fashion-store-d2417.firebasestorage.app',
    measurementId: 'G-5D9V1Q1DYR',
  );

}